### ISSUE TITLE
Generate sas-token function report error

### ISSUE THREAD

**Issue by rainmanwy** [Azure/iothub-explorer#1]
I use npm to install the latest iothub-explorer. But met problem when use sas-token command.
`iothub-explorer sas-token bc_1 -l "xxxx"
/usr/local/lib/node_modules/iothub-explorer/iothub-explorer-sas-token.js:44
    var key = device.authentication.SymmetricKey.primaryKey || device.authentication.SymmetricKey.secondaryKey;
                                                ^

TypeError: Cannot read property 'primaryKey' of undefined
    at /usr/local/lib/node_modules/iothub-explorer/iothub-explorer-sas-token.js:44:49
    at /usr/local/lib/node_modules/iothub-explorer/node_modules/azure-iothub/lib/registry.js:223:7
    at /usr/local/lib/node_modules/iothub-explorer/node_modules/azure-iothub/lib/rest_api_client.js:109:7
    at IncomingMessage.onResponseEnd (/usr/local/lib/node_modules/iothub-explorer/node_modules/azure-iot-http-base/lib/http.js:73:7)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
`

Note: i am using iothub-explorer to access iothub in China.
The old explorer version works fine.

**Comment by pierreca** [comment]
By any chance are you using the SDK version 1.1.0? We fixed a bug within the Device class recently that fixes exactly that problem and would fix iothub-explorer too. can you try with the latest released version (1.1.2)?

**Comment by pierreca** [comment]
Closing as the fix is checked in - will be released as npm package in the next couple of days
