### ISSUE TITLE
Encoding issue when sending JSON with send command

### ISSUE THREAD

**Issue by qrdemole** [Azure/iothub-explorer#10]
I'm trying to send json: `{"messageType":"SomeType"}` with the send command
Tried:

1. `iothub-explorer send MyDeviceId '{"messageType":"SomeType"}'`
2. `iothub-explorer send MyDeviceId "{\"messageType\":\"SomeType\"}"`
3. `` iothub-explorer send MyDeviceId `cat data.txt` `` 
In case 3 I tried loading from file with utf and ascii encoding

Every time my client receives IMHO incorrect string in bytes: `\xc1\x18\x02\xa1\x0bmessageType\xa1\x08SomeType`
So it seems to be incorrect at the beginning and also it seems to be truncated. I can't convert it in any encoding 

If I replace characters `{` and `"` with something alphanumeric it seems to be sent correctly
Also if I send `'"'`, `'{'`,`'}'` alone it seems to be sent correctly, but `'{}'` results in `\xc1\x01\x00`

**Comment by pierreca** [comment]
@qrdemole what OS and command line shell are you running the command from (not sure it's relevant yet but asking to get an accurate repro)

**Comment by qrdemole** [comment]
I'm using bash on Ubuntu 16.04 LTS

Additionally sending the same message from the device explorer (https://github.com/Azure/azure-iot-sdks/releases -> SetupDeviceExplorer.msi)  and from a .NET app using the Microsoft.Azure.Devices.ServiceClient works fine, so it seems that it is not the target device issue.

**Comment by pierreca** [comment]
Yup, Looks like one of those cases where tried to be too smart for our own good. What happens is that the JSON is parsed, and then passed onto the AMQP library without serializing it, which means what gets sent over the wire is the non-serialized javascript object. We'll have a fix shortly. Thanks a lot for reporting this!!

**Comment by pierreca** [comment]
@qrdemole would you mind pulling the latest from the repo and testing if the fix works for you?
once you've cloned the repo, you can just run `npm install -g .` from within the repo to install it or simply run `node iothub-explorer.js <command>` .

Thanks!

**Comment by qrdemole** [comment]
It works now.
Thx for such quick responses and fixing the bug!
