### ISSUE TITLE
iothub-explorer monitor-events {device} catches other device events

### ISSUE THREAD

**Issue by forthlightning** [Azure/iothub-explorer#15]
When I run the command

` iothub-explorer monitor-events --login=$MYKEY MyThing001 `

I see events from both MyThing001, and MyThing002 stream across the terminal.

This is confusing when I am trying to debug a certain device.

I have confirmed that each device is publishing using its own connection string to its own device endpoint.

Pls to halp.

```
==== From: MyThing001 ====
"message content"
---- properties ----
{}
====================
==== From: MyThing001 ====
"message content"
---- properties ----
{}
====================
==== From: MyThing001 ====
"message content"
---- properties ----
{}
====================
==== From: MyThing002 ====
"message content"
---- properties ----
{}
====================
==== From: MyThing002 ====
"message content"
---- properties ----
{}
====================
```

**Comment by pierreca** [comment]
I think that bug was supposed to be fixed with the latest version (https://github.com/Azure/iothub-explorer/commit/388f39896f7cfd874617bd01d78b17913ae66a3f) 
can you please confirm you are using version 1.1.10?

**Comment by forthlightning** [comment]
nope just updated and ran a test and it works :D :D
