### ISSUE TITLE
iothub-explorer not sending message such that it can be received by AMQP client.

### ISSUE THREAD

**Issue by darobs** [Azure/iothub-explorer#19]
# Context
$ node --version
v7.10.0
$ iothub-explorer --version
1.1.12
$ npm --version
4.2.0
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
(and Windows, as well)

# Description of the issue:

`iothub-explorer send _mydevice_  {"type": "write_once", "characteristic_uuid": "E95D93EE-251D-470A-A062-FA1922DFA9A8", "data": "aGFsbG8="}`

The message sent is rejected by the C SDK AMQP client.

However, if the same message body is put into the Device explorer or Azure portal, the message is accepted.

Also, made a few other attempts with the command line, did things like:

```
iothub-explorer send _mydevice_  '{"type": "write_once", "characteristic_uuid": "E95D93EE-251D-470A-A0
62-FA1922DFA9A8", "data": "aGFsbG8="}'
iothub-explorer send _mydevice_  "{\"type\": \"write_once\", \"characteristic_uuid\": \"E95D93EE-251D-
470A-A062-FA1922DFA9A8\", \"data\": \"aGFsbG8=\"}"
```

**Comment by pierreca** [comment]
See https://github.com/Azure/iothub-explorer/issues/18 and https://github.com/Azure/azure-iot-sdk-c/issues/146
