### ISSUE TITLE
Sending message to IoT Hub from Mac

### ISSUE THREAD

**Issue by AdamSzendrei** [Azure/iothub-explorer#22]
I'm trying to send messages to the IoT Hub without Raspberry Pi on my Mac.

I would like to login iothub-explorer, but it is not clear where can I find the 
**SharedAccessKeyName=<my-policy>;**
The link in the Git repository doesn't exist anymore: https://github.com/Azure/iothub-explorer/doc/setup_iothub.md

On the GitHub site:
"Note: See Set up IoT Hub for information about how to retrieve your IoT hub connection string."
iothub-explorer login "HostName=<my-hub>.azure-devices.net;**SharedAccessKeyName=<my-policy>;**SharedAccessKey=<my-policy-key>"

**Comment by anthonyvercolano** [comment]
go to the portal

Select the hub you care about.

Under Settings -> Shared Access Policies you should see a IoTHubOwner

Select that.  You should see, on the right an entry for ConnectionString - Primary Key.

Use that connection string to log in.

**Comment by AdamSzendrei** [comment]
Thanks!

**Comment by tameraw** [comment]
@AdamSzendrei - Thanks for reporting this. Also, the link has been fixed.
