### ISSUE TITLE
From where is that "windSpeed": 15.20" and "windSpeed": 15.77" are coming?

### ISSUE THREAD

**Issue by Canalytix** [Azure/iothub-explorer#24]
# Context
- **OS and version used:** <VERSION> 
- **Node.js version:** <VERSION> 
- **npm version:** <VERSION> 
- **list of installed packages:** <VERSION> 
- **cloned repo:** <VERSION> 

# Description of the issue:

# Console log of the issue:

# Code sample exhibiting the issue:

**Comment by anthonyvercolano** [comment]
Could you please give a bit more explanation?

**Comment by Canalytix** [comment]
Sorry for being very fast, I'm totally new to this
I was trying to establish a connection between my simulated device and the IoT hub using the sample python script copied from this https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-python-getstarted
I followed all the steps.

At the end I used "Device explorer" (https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/DeviceExplorer) as I was not able to install IoT hub explorer 
In the "data" tab of the Device explorer I see this

7/14/2017 5:48:23 PM> Device: [MyFirstPythonDevice], Data:[{"deviceId": "MyFirstPythonDevice","windSpeed": 15.20}]Properties:

'Property': 'PropMsg_0'



7/14/2017 5:48:53 PM> Device: [MyFirstPythonDevice], Data:[{"deviceId": "MyFirstPythonDevice","windSpeed": 15.77}]Properties:

'Property': 'PropMsg_1'

which you can find from the same link https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/DeviceExplorer 

Now from where is this "windSpeed": 15.20 and "windSpeed": 15.77 are coming?
Because I don't see it in my python script.

Is it because of Device Explorer or IoT hub explorer?

Also please tell me, am I wrong in assuming, it's my python script (SimulatedDevice.py) that is sending the "device-to-cloud" message.

**Comment by anthonyvercolano** [comment]
In https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-python-getstarted section 7 there is a large code block.

The first line of the while TRUE block would seem to be createing the whole windspeed text.  I'm assuming you created the python sample as suggested in the article.

**Comment by pierreca** [comment]
@Canalytix looks like @anthonyvercolano found your answer, closing but feel free to reopen the issue if that wasn't it.
