### ISSUE TITLE
Generates bad JSON array when more than one item being printed

### ISSUE THREAD

**Issue by raykao** [Azure/iothub-explorer#26]
https://github.com/Azure/iothub-explorer/blob/f52519ed6bca474571c10bd6a213bdcc1672c539/common.js#L138

While this will out valid JSON for one object in console, however it will generate invalid JSON when you return an array of objects.

**Comment by pierreca** [comment]
feedback given directly on the PR - will close after requested changes have been made and the PR is merged.

**Comment by pierreca** [comment]
Closing after merging #27
