### ISSUE TITLE
Monitor-events should check that a device exists before going into monitor mode.

### ISSUE THREAD

**Issue by WilliamBerryiii** [Azure/iothub-explorer#30]
Monitor-events, and likely other methods, should check that a device exists before going into monitor mode.

Repro:
`iothub-explorer monitor-events {device-id-that-doesnt-exist} --login "{connection-string}"

**Comment by pierreca** [comment]
That's fair - we would happily review/accept a pull request for that.

**Comment by WilliamBerryiii** [comment]
@digimaun ... got any bandwidth for an enhancement request here?

**Comment by digimaun** [comment]
@WilliamBerryiii Let me get back to you on that soon

**Comment by damonbarry** [comment]
Since I was just in that code for another pull request, I created a pull request to fix this one too.

**Comment by pierreca** [comment]
Fixed with #33

**Comment by pierreca** [comment]
Fixed in version 1.1.19 released on 2017-11-29
