### ISSUE TITLE
Short form options not recognized

### ISSUE THREAD

**Issue by dluc** [Azure/iothub-explorer#34]
# Context
- **OS and version used:** MacOS 10.13.2
- **Node.js version:** v9.2.1
- **npm version:** 5.6.0
- **iothub-explorer version:** 1.1.15

# Description of the issue:

Short form options are not working, for example:

```
iothub-explorer monitor-events -cg cli -l "HostName=...;SharedAccessKeyName=iothubowner;SharedAccessKey=..."
```
returns
```
error: unknown option `-c'
```

and

```
iothub-explorer monitor-events -st "..." -l "HostName=...;SharedAccessKeyName=iothubowner;SharedAccessKey=..."
```
returns
```
error: unknown option `-s'
```

**Comment by pierreca** [comment]
Fixed with #35 and v1.1.20
Thanks for reporting this!
