### ISSUE TITLE
Inconsistent command line parsing between powershell and cmd

### ISSUE THREAD

**Issue by WilliamBerryiii** [Azure/iothub-explorer#38]
# Context
- **OS and version used:** Windows 10
- **Node.js version:** 9.0
- **npm version:** 5.5.1

# Description of the issue:
There is inconsistent command line parsing between powershell and cmd for connection strings.  When using the following command:

iothub-explorer monitor-events {device} --login HostName={host name}.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey={key}

If the connection information is surrounded with single quotes in a CMD window, the following error is thrown: 
`throw new ArgumentError('Connection string doesn\'t have EntityPath, or missing argument path');`

Powershell handles no quoting, single, and double quotes.

**Comment by pierreca** [comment]
@WilliamBerryiii sounds like this is an issue with how quotes are handled by the shell, not iothub-explorer? What behavior would you like to see?

**Comment by WilliamBerryiii** [comment]
I've not fully investigated the behavior across shells; but my hunch is that the connection string for the CMD when using single quotes is like passing the single quotes in along with the connection information.  My guess is that we simply trim all forms of quotes from the login string, everything will work as expected.

**Comment by pierreca** [comment]
Ohh I see - single quotes are required for powershell because it treats the ';' as the end of the command whereas DOS doesn't care. But single quotes are not interpreted by DOS that considers them part of the connection string and fails. therefore the same program cannot run both in powershell and DOS. mutual exclusion. And trimming single quotes would solve that. is that it?

**Comment by pierreca** [comment]
@WilliamBerryiii given we're going to be moving everything to the azure cli, i'm closing this as won't fix.
