### ISSUE TITLE
Error: At least one receiver for the endpoint is created with epoch of '1' when monitoring events

### ISSUE THREAD

**Issue by tylerl0706** [Azure/iothub-explorer#40]
# Context
- **OS and version used:** Windows 10 
- **Node.js version:** v6.11.0 
- **npm version:** 3.10.10 
- **list of installed packages:** empty 
- **cloned repo:** N/A 

# Description of the issue:

I was running:
```
iothub-explorer.cmd monitor-events --login "<connstr>"
```

# Console log of the issue:

With DEBUG:
```
amqp10:client session error:  { AmqpProtocolError: amqp:link:stolen:At least one receiver for the endpoint is created with epoch of '1', and so non-epoch receiver is not allowed. Either reconnect with a higher epoch, or make sure all epoch receivers are closed or disconnected.
Timestamp:1/12/2018 8:31:20 PM , Timestamp:1/12/2018 8:31:20 PM
    at Object.errors.wrapProtocolError (C:\Users\tyleonha\AppData\Roaming\npm\node_modules\iothub-explorer\node_modules\amqp10\lib\errors.js:10:12)
    at ReceiverLink.Link._detached (C:\Users\tyleonha\AppData\Roaming\npm\node_modules\iothub-explorer\node_modules\amqp10\lib\link.js:221:42)
    at ReceiverLink.Link._detachReceived (C:\Users\tyleonha\AppData\Roaming\npm\node_modules\iothub-explorer\node_modules\amqp10\lib\link.js:204:8)
    at Session._processDetachFrame (C:\Users\tyleonha\AppData\Roaming\npm\node_modules\iothub-explorer\node_modules\amqp10\lib\session.js:335:45)
    at Session._processFrame (C:\Users\tyleonha\AppData\Roaming\npm\node_modules\iothub-explorer\node_modules\amqp10\lib\session.js:302:61)
    at Connection._processFrameEH (C:\Users\tyleonha\AppData\Roaming\npm\node_modules\iothub-explorer\node_modules\amqp10\lib\session.js:186:49)
    at emitOne (events.js:101:20)
    at Connection.emit (events.js:188:7)
    at Connection._receiveAny (C:\Users\tyleonha\AppData\Roaming\npm\node_modules\iothub-explorer\node_modules\amqp10\lib\connection.js:426:12)
    at Connection._receiveData (C:\Users\tyleonha\AppData\Roaming\npm\node_modules\iothub-explorer\node_modules\amqp10\lib\connection.js:357:8)
    at TlsTransport.<anonymous> (C:\Users\tyleonha\AppData\Roaming\npm\node_modules\iothub-explorer\node_modules\amqp10\lib\connection.js:515:38)
    at emitOne (events.js:96:13)
    at TlsTransport.emit (events.js:188:7)
    at TLSSocket.<anonymous> (C:\Users\tyleonha\AppData\Roaming\npm\node_modules\iothub-explorer\node_modules\amqp10\lib\transport\tls_transport.js:29:49)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
  name: 'AmqpProtocolError',
  message: 'amqp:link:stolen:At least one receiver for the endpoint is created with epoch of \'1\', and so non-epoch receiver is not allowed. Either reconnect with a higher epoch, or make sure all epoch receivers are closed or disconnected., Timestamp:1/12/2018 8:31:20 PM  Timestamp:1/12/2018 8:31:20 PM',
  condition: 'amqp:link:stolen',
  description: 'At least one receiver for the endpoint is created with epoch of \'1\', and so non-epoch receiver is not allowed. Either reconnect with a higher epoch, or make sure all epoch receivers are closed or disconnected. Timestamp:1/12/2018 8:31:20 PM',
  errorInfo: {} } +1ms
```

**Comment by pierreca** [comment]
that's a new one - thanks for reporting it!
is it happening often? all the time? only very rarely? any circumstances that make it easy to reproduce the issue?

**Comment by tylerl0706** [comment]
It happens every time. I'm not sure what the circumstances would be... I was remoted into my raspberry Pi that was sending requests so maybe that might cause something?

**Comment by pierreca** [comment]
can you break down what the setup was exactly? I can try and repro the issue, but i've never encountered it.

You had a raspberry pi, sending requests over AMQP, and then you remoted into it, and started iothub-explorer monitor-events, and then this happens? is that correct?

**Comment by tylerl0706** [comment]
Hey! I spoke to @noopkat and she says (correct me if I have the wording wrong!) that usually this issue happens when iothub-explorer is using the default consumer group because Azure IoT Suite is usually listening on the default already. 

Once I added a new consumer group and started listening on that, everything started working. We can close this if you want, but it would be awesome if the error message out of iothub-explorer was just a little bit friendlier!

**Comment by pierreca** [comment]
Oh I see - thanks @noopkat !
The error message is what we get from the server, we don't translate it right now - we should be able to modify iothub-explorer to intercept that link-stolen error and print a suggestion to use a different consumer group though.

seems like a fairly easy modification, would you like to try and contribute it?

**Comment by tylerl0706** [comment]
@pierreca Yeah! I can do that. Any idea what you want the suggestion to say?

Maybe like

```
ERROR: amqp:link:stolen:At least one receiver for the endpoint is created with epoch of \'1\',
and so non-epoch receiver is not allowed. Either reconnect with a higher epoch,
or make sure all epoch receivers are closed or disconnected.

This issue can occur if you have two services listening in the same consumer group.
Specify a different consumer group with the `-c` flag.
Ex. `iothub-explorer monitor-events --login "<connstr>" -c testGroup`
```

I wanted to add a link to docs on consumer groups but I couldn't find one. Any idea where one is?

**Comment by pierreca** [comment]
@tylerl0706 Thanks! Here's what I could find for consumer groups: https://github.com/MicrosoftDocs/azure-docs/blob/master/includes/iot-hub-get-started-create-consumer-group.md

 I like  your suggestion, it's helpful. you should go with that.

**Comment by tylerl0706** [comment]
@pierreca PR out now :)

**Comment by kgosalia** [comment]
@tylerl0706 Hi there, I have a Raspberry Pi deployed on the IoT Hub and when I try to monitor events, its giving me the same error message. After going through the comments I successfully added a new consumer group. My question is, how do I make it hear on the new endpoint. Any ideas?

**Comment by pierreca** [comment]
@kgosalia  you can use the `-c` option of the `monitor-events` command to specify a consumer group.
See: https://github.com/Azure/iothub-explorer/blob/master/iothub-explorer-monitor-events.js#L43

**Comment by kgosalia** [comment]
@pierreca Thanks for sending over that link. I tried the new command syntax, and the problem now is I think the connection is timed out. There is neither an error message nor the command works. If you want I can send an attachment of my cmd prompt window screenshot.

**Comment by pierreca** [comment]
@kgosalia please open an new issue then describing the commands you run and the results you see (console logs preferable). if you want you can activate detailed tracing by setting the `DEBUG` environment variable to `*`. Make sure to weed out anything confidential from the logs if you paste this. thanks.
