### ISSUE TITLE
monitor-events should show timestamp when event was received

### ISSUE THREAD

**Issue by stefannilsson** [Azure/iothub-explorer#42]
If events are being received at irregular intervals the timestamp would help while developing/testing/troubleshooting.

Now:
```
==== From: node-01 ====
{
  "TJ1": 10.1,
  "T1": 10.2,
  "T2": 10.3,
  "t": 1517009997437
}
====================
```

Proposal:
```
==== From: 'node-01' at '2018-01-27T00:44:00Z' ====
{
  "TJ1": 10.1,
  "T1": 10.2,
  "T2": 10.3,
  "t": 1517009997437
}
====================
```

**Comment by pierreca** [comment]
PR was merged, thanks for sending it! we will release a new package in the coming days.

**Comment by pierreca** [comment]
Closed with release https://github.com/Azure/iothub-explorer/releases/tag/2018-2-7
Thanks again!!
