### ISSUE TITLE
Add a short alias (e.g. `iotex`)

### ISSUE THREAD

**Issue by lucaslra** [Azure/iothub-explorer#47]
# Context
- **OS:** All
- **SUGGESTION**

## Disclaimer
This is more a suggestion than an actual issue, but I couldn't find a more appropriated channel for it.

# Description of the issue:
It is really cumbersome to be typing `iothub-explorer` many times (or editing some command on the prompt history)

**Comment by pierreca** [comment]
@lucaslra see my comment on your PR.
I would rather leave aliasing to the user's shell preferences. for example in your .bashrc file:
```sh
alias iotex=iothub-explorer
```

**Comment by lucaslra** [comment]
I accept the answer, but I still think that an out-of-the-box alias helps a lot.
