### ISSUE TITLE
View SAS Token Expirations for Devices Registered to IoT Hub

### ISSUE THREAD

**Issue by adingman** [Azure/iothub-explorer#49]
I’m using an IIoT solution called KepServerEX to send data from our Programmable Logic Controllers to the Azure IoT Hub. 

I’m generating SAS Tokens using the IoT Hub Explorer for each “device” set-up in the KepServerEX software. While I’m setting expirations for the tokens, I don’t seem to have a way to review all the tokens I’ve generated along with the expiration time of the token. 

Is this something that this utility will support in the future? Any other suggestions?

I’m fearful that a token will expire unknowingly and will cause an unnecessary outage in data streaming into the IoT Hub.

**Comment by adingman** [comment]
@pierreca this certainly helps! Unfortunately, this KepServerEX application does not currently allow for the use of the SDKs so that leads me to the sas token broker service which is not something I'd particularly like to manage.

I also explored the option of using the x.509 certificates. However, I didn't see any method to update the thumbprint associated to a device registered to the IoT Hub at the point that the certificate expired and a new one was generated. It appears the device would have to be deleted and re-created using the new thumbprint.

**Comment by pierreca** [comment]
@adingman 

WRT to updating expired certificates: you can keep the device identity in the registry and just update it with a new thumbprint, that's totally possible. you'd have to have a way to send the new certificate to the device though (and that's where a provisioning service might be useful - see question 3 below)

additional questions:
1. what would be the requirements of this "SAS token cache"? just a quick session thing that disappears after a specific time limit, or something that is permanent and takes care of all devices on the hub and that you can refer to over time?
2. have you considered having the devices provisioned with their symmetric key and letting the device SDK generate the SAS tokens?
3. If you're still considering the certificate route, have you looked at the [Device Provisioning Service](https://docs.microsoft.com/en-us/azure/iot-dps/about-iot-dps) and how maybe it could help with your scenario?

**Comment by pierreca** [comment]
closing after some inactivity - happy to reopen later if more comes to mind.
