### ISSUE TITLE
Problem Sending Commands using Direct method

### ISSUE THREAD

**Issue by samisarfraz** [Azure/iothub-explorer#56]
This is a bit weird and confusing issue but i'll try to explain it.I am facing a problem in sending commands using direct method (invoke method). We developed our code with azure c sdk (Arduino) and was able to send commands with Direct method (Method name + payload) when using Portal.Azure.com or windows 7 machine using device explorer. Initially we were using this feature from cloud (Direct method) then we shifted to device explorer as its easy to use. Device explorer was working fine on windows 7. We can send commands with method name and payload. But when we installed device explorer on windows 10 things got very peculiar as we only invoke a command with only method name (no payload). When we send the command with method name and payload (json string) it cause our device to restart and shows an error but these very same commands { method name and payload (json string)} execute fully when we send them from windows 7 device explorer or portal.azure.com – direct method / invoke method (no restart or errors) . We are facing the same problem when we use the sdks (java , node , C#) for sending commands.

**Comment by pierreca** [comment]
sounds like in that case it's a serialization issue that doesnt have anything to do with iothub-explorer, doesn't it? 
isn't the simplest way to debug this to hook up a debugger to the device and see what is received?

**Comment by samisarfraz** [comment]
Thanks for the quick reply. but as you can see I've mentioned that we can invoke methods from azure portal and they are working very fine. The device explorer invokes method perfectly in windows 7 but the very same explorer is causing the problem in windows 10 and so are the SDKs. On the other hand the latency is very high in azure ( avg. 6 secs). In these circumstances we have no choice other than moving to other iot platform 
Thanks.
