### ISSUE TITLE
StatusCode 400 in Node-RED Authentication information is not given in the correct format. Check the value of Authorization header.

### ISSUE THREAD

**Issue by mcppp** [Azure/iothub-explorer#58]
Hello. I am trying to create a PUT Request to create blobs in the Blob Storage Account I have in Microsoft Azure. The problem is that I don't know how to structure or where to enter the SAS Token I get from my storage account in Microsoft. I am supposed to modify the header of the http Request in Node-RED (I think) but all the ways I have tried give me the error :

`﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidAuthenticationInfo</Code><Message>Authentication information is not given in the correct format. Check the value of Authorization header.RequestId:ffd87299-a01e-00a3-1b8f-ef8523000000Time:2019-04-10T11:23:04.7283176Z</Message></Error>`

I have tried all possible ways and googled a lot but I cannot find out what the correct structure is. Right now I have this in the node for the HTTP Request:

`https://<accountname>.blob.core.windows.net/mycontainer5/DocumentTest.txt<SAS Token>`

and I have added a function node before the HTTP Request node as an attempt to change the header:

```
msg.headers = {};
msg.headers['x-ms-blob-type'] = 'BlockBlob';
msg.headers['Authorization'] = 'SharedAccessSignature sig=EcJHGw4LhFeghTr1m7w7IiNZ1UQ1z';
return msg;
```

Any help is welcome cause I am stuck since many days. Thanks.

**Comment by pierreca** [comment]
@mcppp this sounds like a question for the storage team - i'm not sure what led you here but I have no idea what you're talking about. this repository is about a deprecated IoT tool that has nothing to do with storage. i'd suggest asking there: https://github.com/Azure/azure-storage-node

Closing as off-topic.
